language: node_js

branches:
  only:
    - master
    - develop

node_js:
  - 5
  - 6
  - 7

before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g bower-npm-resolver

install:
  - npm install
  - bower install

script: grunt check
